version: '2.1'
services:
  telegraf:
    build: ./telegraf
    environment:
      - INFLUX_ADDRESS=influxdb:8086
      - MODBUS_GATEWAY_IP=192.168.1.63
      - L1_NAME=L1
      - L2_NAME=L2
      - L3_NAME=L3
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125/udp'

  influxdb:
    build: ./influxdb
    volumes: 
      - 'influxdb_data:/var/lib/influxdb2'
    #env_file: configuration.env
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      # The TLS or SSL certificate to use when HTTPS is enabled.
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/influxdb-selfsigned.crt
      # Use a separate private key location.
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/influxdb-selfsigned.key
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    ports:
      - '8086:8086'

  # ui:
  #   build: .
  #   environment:
  #     - HTTP_PORT=80
  #     - HTTPS_PORT=443
  #   network_mode: "host"

  # tailscale:
  #   build:
  #     context: ./tailscale-balena-block
  #     dockerfile: Dockerfile.template
  #   restart: always
  #   network_mode: host
  #   volumes:
  #     - tailscale-state:/tailscale

volumes:
  influxdb_data: {}
  # tailscale-state: {}
