version: '3.6'
services:
  telegraf:
    image: telegraf:1.18
    environment:
      - MODBUS_GATEWAY_IP=192.168.8.123
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125/udp'

  influxdb:
    build: ./influxdb
    env_file: configuration.env
    ports:
      - '8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  # grafana:
  #   image: grafana/grafana:8.0.2
  #   depends_on:
  #     - influxdb
  #   env_file: configuration.env
  #   links:
  #     - influxdb
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #     - ./grafana/provisioning/:/etc/grafana/provisioning/
  #     - ./grafana/dashboards/:/var/lib/grafana/dashboards/
  
  ui:
    build: .
    ports:
      - "8080:8080"

volumes:
  grafana_data: {}
  influxdb_data: {}
