version: '2.1'
services:
  telegraf:
    build: ./telegraf
    environment:
      - INFLUX_ADDRESS=influxdb:8086
      - MODBUS_GATEWAY_IP=192.168.8.123
      - L1_NAME=L1
      - L2_NAME=L2
      - L3_NAME=L3
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125/udp'

  influxdb:
    build: ./influxdb
    #env_file: configuration.env
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      # The TLS or SSL certificate to use when HTTPS is enabled.
      - INFLUXDB_HTTP_HTTPS_CERTIFICATE=/etc/ssl/influxdb-selfsigned.crt
      # Use a separate private key location.
      - INFLUXDB_HTTP_HTTPS_PRIVATE_KEY=/etc/ssl/influxdb-selfsigned.key
    ports:
      - '8086:8086'

  ui:
    build: .
    environment:
      - HTTP_PORT=80
      - HTTPS_PORT=443
    network_mode: "host"

  tailscale:
    build:
      context: ./tailscale-balena-block
      dockerfile: Dockerfile.template
    restart: always
    network_mode: host
    volumes:
      - tailscale-state:/tailscale

volumes:
  influxdb_data: {}
  tailscale-state: {}
